# Generated by Django 4.2 on 2026-05-02 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_gallery_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
